### ISSUE TITLE
Can't open any file

### ISSUE THREAD

**Issue by ojm-it** [bingtimren/vscode-tidy-explorer#1]
Hello,

I was trying out your extension and I found out that clicking on a file doesn't open it in the editor. Also, the right-click doesn't show the contextual menu.

Is this expected behavior?

**Comment by bingtimren** [comment]
Hi

Thanks for reporting this issue.

I fixed the issue of clicking a file does not open it in the editor. Please upgrade the extension to 1.2.1 and give it a try. Let me know if it works for you. Thanks!

Context menu is not supported.
