### ISSUE TITLE
Multi-root workspace support

### ISSUE THREAD

**Issue by calonx** [bingtimren/vscode-tidy-explorer#2]
I have multiple folders in a workspace, but the "Pockets" only seem to apply to the first folder. Any chance that feature could be extended to support this scenario?

**Comment by bingtimren** [comment]
Hey thanks for downloading my plugin. This plugin supports multi-root workspace. If you define the Pockets in the settings for the first folder, then it works on the first folder only. If you define the Pockets in the settings for the second folder, it works on the second folder only. If you define the Pockets in the user or workspace settings, then it works on both folders. 

In the screenshot of the README you can see "User", "Workspace" and "Folder" on VS Code settings dialog. Use it to choose between user, workspace and workspace folder settings.

See [https://code.visualstudio.com/docs/getstarted/settings#_workspace-settings](https://code.visualstudio.com/docs/getstarted/settings#_workspace-settings)

**Comment by calonx** [comment]
Hmm, now that I'm probing this again, everything looks as it's supposed to be... My best guess is that I neglected to refresh the Tidy Explorer panel. 😕 Apologies! I appreciate the response, thank you!

Quick note: case-insensitive sorting within Tidy Explorer would be awesome. Is that option available?
